In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('data.csv')
df.columns

Index(['timestamp,open,high,low,close,volume_btc,volume_usd'], dtype='object')

In [6]:
df

     timestamp,open,high,low,close,volume_btc,volume_usd
0     2024-01-01 00:00:00,44910.83,45085.78,44910.83...
1     2024-01-01 00:01:00,44977.19,45045.33,44977.19...
2     2024-01-01 00:02:00,44991.38,45103.85,44965.65...
3     2024-01-01 00:03:00,45056.78,45135.78,45056.78...
4     2024-01-01 00:04:00,45172.02,45222.19,44979.72...
...                                                 ...
9995  2024-01-07 22:35:00,44139.5,44187.67,44102.45,...
9996  2024-01-07 22:36:00,44165.1,44177.54,43928.89,...
9997  2024-01-07 22:37:00,44083.32,44083.32,43977.78...
9998  2024-01-07 22:38:00,44057.8,44196.97,43879.32,...
9999  2024-01-07 22:39:00,44061.71,44220.17,44057.19...

[10000 rows x 1 columns]

In [18]:
cols = ["timestamp","open","high","low","close","volume_btc","volume_usd"]

df = df.str.split(",", expand=True)
df.columns = cols

AttributeError: 'DataFrame' object has no attribute 'str'

In [19]:
df.columns = cols

In [20]:
df

,timestamp,open,high,low,close,volume_btc,volume_usd
0,2024-01-01 00:00:00,44910.83,45085.78,44910.83,45024.68,3.640837,163927.55
1,2024-01-01 00:01:00,44977.19,45045.33,44977.19,45017.83,33.752474,1519463.07
2,2024-01-01 00:02:00,44991.38,45103.85,44965.65,45050.03,5.488855,247273.08
3,2024-01-01 00:03:00,45056.78,45135.78,45056.78,45125.82,8.464271,381957.14
4,2024-01-01 00:04:00,45172.02,45222.19,44979.72,45114.17,21.673405,977777.67
...,...,...,...,...,...,...,...
9995,2024-01-07 22:35:00,44139.5,44187.67,44102.45,44153.42,8.046188,355266.76
9996,2024-01-07 22:36:00,44165.1,44177.54,43928.89,44056.18,7.117921,313588.41
9997,2024-01-07 22:37:00,44083.32,44083.32,43977.78,44021.92,15.644622,688706.27
9998,2024-01-07 22:38:00,44057.8,44196.97,43879.32,44046.02,10.999206,484471.26
9999,2024-01-07 22:39:00,44061.71,44220.17,44057.19,44077.36,71.787946,3164223.36

In [23]:
df.to_csv('data.csv', index=False)

In [ ]:
df=df

object